# inference_config.yaml

############ LLaMA2 7B ################
inference_parcel:
  # ModelArguments
  model_name_or_path: /path/to/best/llama2/model/checkpoint/dir
  freeze_LM: true
  model_4bit: false
  img_token_num: 2
  img_input_channel: 15
  resnet_depth: 50
  resnet_fc_dim: 2048
  # TrainingArguments
  img_type: parcel
  wandb_project: MedicalCoT
  wandb_name: llama2_parcel_test
  save_dir: pytorch_lightning/checkpoint/save/dir
  devices: [0,1,2,3,4,5]
  max_epochs: 50
  do_train: false
  do_test: true
  lr: 0.00005
  scheduler_type: ReduceLROnPlateau
  strategy: deepspeed_stage_2
  # data
  source_max_len: 1024
  target_max_len: 1024
  predict_with_generate: false
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  predict_with_generate: true
  save_prediction_file: /path/to/save/prediction/json/file

inference_parcel_resnet152:
  # ModelArguments
  model_name_or_path: /path/to/best/llama2/model/checkpoint/dir
  freeze_LM: true
  model_4bit: false
  img_token_num: 2
  img_input_channel: 15
  resnet_depth: 152
  resnet_fc_dim: 512
  # TrainingArguments
  img_type: parcel
  wandb_project: MedicalCoT
  wandb_name: llama2_parcel_resnet152_test
  save_dir: pytorch_lightning/checkpoint/save/dir
  devices: [0,1,2,3]
  max_epochs: 50
  do_train: false
  do_test: true
  lr: 0.00005
  scheduler_type: ReduceLROnPlateau
  strategy: deepspeed_stage_2
  # data
  source_max_len: 1024
  target_max_len: 1024
  predict_with_generate: false
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  predict_with_generate: true
  save_prediction_file: /path/to/save/prediction/json/file

inference_parcel_llama2_wo_rationale:
  # ModelArguments
  model_name_or_path: /path/to/best/llama2/model/checkpoint/dir
  freeze_LM: true
  model_4bit: false
  img_token_num: 2
  img_input_channel: 15
  resnet_depth: 50
  resnet_fc_dim: 2048
  # TrainingArguments
  img_type: parcel
  wandb_project: MedicalCoT
  wandb_name: llama2_parcel_wo_rationale_test
  save_dir: pytorch_lightning/checkpoint/save/dir
  devices: [0,1,2,3,4,5]
  max_epochs: 50
  do_train: false
  do_test: true
  lr: 0.00005
  scheduler_type: ReduceLROnPlateau
  strategy: deepspeed_stage_2
  # data
  source_max_len: 1024
  target_max_len: 1024
  predict_with_generate: false
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  predict_with_generate: true
  save_prediction_file: /path/to/save/prediction/json/file

############### OPT1.3B #####################
inference_parcel_opt1:
  # ModelArguments
  model_name_or_path: /path/to/best/opt1.3b/model/checkpoint/dir
  freeze_LM: true
  model_4bit: false
  img_token_num: 4
  img_input_channel: 15
  resnet_depth: 50
  resnet_fc_dim: 2048
  # TrainingArguments
  img_type: parcel
  wandb_project: MedicalCoT
  wandb_name: opt6_parcel_test
  save_dir: pytorch_lightning/checkpoint/save/dir
  devices: [0,1,2,3,4,5]
  max_epochs: 50
  do_train: false
  do_test: true
  lr: 0.00005
  scheduler_type: ReduceLROnPlateau
  strategy: deepspeed_stage_2
  # data
  source_max_len: 1024
  target_max_len: 1024
  predict_with_generate: false
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  predict_with_generate: true
  save_prediction_file: /path/to/save/prediction/json/file

inference_parcel_opt1_resnet152:
  # ModelArguments
  model_name_or_path: /path/to/best/opt1.3b/model/checkpoint/dir
  freeze_LM: true
  model_4bit: false
  img_token_num: 2
  img_input_channel: 15
  resnet_depth: 152
  resnet_fc_dim: 512
  # TrainingArguments
  img_type: parcel
  wandb_project: MedicalCoT
  wandb_name: opt6_resnet152_test
  save_dir: pytorch_lightning/checkpoint/save/dir
  devices: [0,1,2,3,4,5]
  max_epochs: 50
  do_train: false
  do_test: true
  lr: 0.00005
  scheduler_type: ReduceLROnPlateau
  strategy: deepspeed_stage_2
  # data
  source_max_len: 1024
  target_max_len: 1024
  predict_with_generate: false
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  predict_with_generate: true
  save_prediction_file: /path/to/save/prediction/json/file

inference_opt1_wo_rationale:
  # ModelArguments
  model_name_or_path: /path/to/best/opt1.3b/model/checkpoint/dir
  freeze_LM: true
  model_4bit: false
  img_token_num: 2
  img_input_channel: 15
  resnet_depth: 50
  resnet_fc_dim: 2048
  # TrainingArguments
  img_type: parcel 
  wandb_project: MedicalCoT
  wandb_name: opt1_parcel_wo_rationale_test
  save_dir: pytorch_lightning/checkpoint/save/dir
  devices: [0,1,2,3,4,5,6,7]
  max_epochs: 50
  do_train: false
  do_test: true
  lr: 0.0002
  scheduler_type: ReduceLROnPlateau
  strategy: deepspeed_stage_2
  # data
  source_max_len: 1024
  target_max_len: 1024
  predict_with_generate: false
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  predict_with_generate: true
  save_prediction_file: /path/to/save/prediction/json/file


############### OPT6.7B #####################

inference_parcel_opt6:
  # ModelArguments
  model_name_or_path: /path/to/best/opt6.7b/model/checkpoint/dir
  freeze_LM: true
  model_4bit: false
  img_token_num: 4
  img_input_channel: 15
  resnet_depth: 50
  resnet_fc_dim: 2048
  # TrainingArguments
  img_type: parcel
  wandb_project: MedicalCoT
  wandb_name: opt6_parcel_test
  save_dir: pytorch_lightning/checkpoint/save/dir
  devices: [0,1,2,3,4,5]
  max_epochs: 50
  do_train: false
  do_test: true
  lr: 0.00005
  scheduler_type: ReduceLROnPlateau
  strategy: deepspeed_stage_2
  # data
  source_max_len: 1024
  target_max_len: 1024
  predict_with_generate: false
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  predict_with_generate: true
  save_prediction_file: /path/to/save/prediction/json/file

inference_parcel_opt6_resnet152:
  # ModelArguments
  model_name_or_path: /path/to/best/opt6.7b/model/checkpoint/dir
  freeze_LM: true
  model_4bit: false
  img_token_num: 2
  img_input_channel: 15
  resnet_depth: 152
  resnet_fc_dim: 512
  # TrainingArguments
  img_type: parcel
  wandb_project: MedicalCoT
  wandb_name: opt6_resnet152_test
  save_dir: pytorch_lightning/checkpoint/save/dir
  devices: [0,1,2,3,4,5]
  max_epochs: 50
  do_train: false
  do_test: true
  lr: 0.00005
  scheduler_type: ReduceLROnPlateau
  strategy: deepspeed_stage_2
  # data
  source_max_len: 1024
  target_max_len: 1024
  predict_with_generate: false
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  predict_with_generate: true
  save_prediction_file: /path/to/save/prediction/json/file

inference_parcel_opt6_wo_rationale:
  # ModelArguments
  model_name_or_path: /path/to/best/opt6.7b/model/checkpoint/dir
  freeze_LM: true
  model_4bit: false
  img_token_num: 2
  img_input_channel: 15
  resnet_depth: 50
  resnet_fc_dim: 2048
  # TrainingArguments
  img_type: parcel
  wandb_project: MedicalCoT
  wandb_name: opt6_parcel_wo_rationale_test
  save_dir: pytorch_lightning/checkpoint/save/dir
  devices: [0,1,2,3,4,5]
  max_epochs: 50
  do_train: false
  do_test: true
  lr: 0.00005
  scheduler_type: ReduceLROnPlateau
  strategy: deepspeed_stage_2
  # data
  source_max_len: 1024
  target_max_len: 1024
  predict_with_generate: false
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  predict_with_generate: true
  save_prediction_file: /path/to/save/prediction/json/file


